# Generated by Django 4.1.4 on 2023-01-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archdesregisterdb',
            old_name='city',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='archdesregisterdb',
            name='current_occupation',
        ),
        migrations.RemoveField(
            model_name='archdesregisterdb',
            name='state',
        ),
        migrations.RemoveField(
            model_name='archdesregisterdb',
            name='upload_cv',
        ),
    ]
