# Generated by Django 4.1.4 on 2023-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_city_archdesregisterdb_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archdesregisterdb',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='archdesregisterdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Register_Architect'),
        ),
    ]
