# Generated by Django 4.1.4 on 2023-01-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addplansdb',
            name='architect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
