# Generated by Django 4.1.4 on 2023-01-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_addplansdb_architect'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddesignsdb',
            name='designer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
